version: "3"

services:
  app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.development
    volumes:
      - ../:/home/node/app
    env_file:
      - ../.env.local
    ports:
      - ${PORT}:${PORT}
      - ${STORYBOOK_PORT}:6006
