FROM node:18-alpine

RUN apk add --no-cache build-base \
    cairo-dev cairo cairo-tools \
    pango-dev \
    jpeg-dev \
    giflib-dev \
    librsvg-dev

USER node

WORKDIR /home/node/app

CMD npm i && npm run prisma:generate && npm run start:dev
